// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var BroadcastChannelJs = require("./broadcast-channel.js");

function make(prim) {
  return new BroadcastChannelJs.BroadcastChannel(prim);
}

exports.make = make;
/* ./broadcast-channel.js Not a pure module */
